name=input("Enter your name:")
print(f"MyName is:{name}")
age=input("Enter your age:")
print(f"Myage is{age}")
ambition=input("Enter your ambition:")
print(f"MyAmbition is{ambition}")
course=input("Enter your course:")
print(f"Mycourse is{course}")
hobbies=input("Enter your hobbies:")
